### ISSUE TITLE
Problem in set.all() method

### ISSUE THREAD

**Issue by iSayeed** [romainsacchi/carculator_bus#1]
Hi, 
I am facing problem running this cell in the notebook (screenshot attached) .  
I think 'BEV-depot' is changed to 'BEV-plugin'. In the bip.powertrains I didn't find 'BEV-depot', that's why It didn't run at first. Then I got error in set.all() method. 
![bus](https://user-images.githubusercontent.com/49028383/119800722-54853d00-bedd-11eb-8d4b-cf7a2dfba144.JPG)

**Comment by romainsacchi** [comment]
You're right. The correct name is "BEV-depot" not "BEV-plugin", but it seems I forgot to change it here.
Should be fixed now.
