### ISSUE TITLE
Problem importing database to brightway2

### ISSUE THREAD

**Issue by iSayeed** [romainsacchi/carculator_bus#2]
Hi, facing an issue in writing the database in the britghtway2. I am importing using the .export_lci_to_bw method. There are always 10 unlinked exchanges which I didn't manage to match. 
![prob 2](https://user-images.githubusercontent.com/49028383/121398412-9be7e080-c955-11eb-8fb0-d2cf0b235bbd.JPG)

This is the output of i.statistics()
![prob 3](https://user-images.githubusercontent.com/49028383/121399003-47913080-c956-11eb-8e68-ac808fdfd296.JPG)

**Comment by romainsacchi** [comment]
Hi,
let me know if using version 0.0.3 from pip fixes your issue.

**Comment by iSayeed** [comment]
yes it is working now, thank you so much :)
