### ISSUE TITLE
Availability of background datasets

### ISSUE THREAD

**Issue by selimyoussry** [romainsacchi/carculator_bus#5]
Hi @romainsacchi, thanks a lot for your work.

I am wondering where to find the datasets referenced in `background_systems.py`, namely
- `S_concentration_fuel.csv`
- `biofuel_share.csv`
- `electricity_mixes.csv`
- `region_mapping.csv`
- `cumulative_electricity_losses.csv`

Also, are there other required data files that I am missing here, but are required to run `carculator_bus`?

Thank you

**Comment by romainsacchi** [comment]
Hi @selimyoussry,

`carculator_bus` depends on `[carculator_utils](https://github.com/romainsacchi/carculator_utils)`.
You should be able to find all the files you need here: https://github.com/romainsacchi/carculator_utils/tree/master/carculator_utils/data

When you pip install carculator_bus, it should therefore install carculator_utils. So, in principle, all the needed files are there. If not, let me know.
